CREATE TABLE MOVIE
(
    ID   IDENTITY PRIMARY KEY,
    UUID VARCHAR(255),
    TITLE VARCHAR(255),
    GENRE VARCHAR(255),
    PRODUCTION_DATE DATE
);

CREATE TABLE RATE
(
    ID              IDENTITY PRIMARY KEY,
    UUID            VARCHAR(255),
    MOVIE           NUMERIC,
    SCORE           NUMERIC(255)
);